Forum/urls.py
from django.urls import path
from Forum import views

app_name = 'Forum'
urlpatterns = [
    path('', views.home, name='home'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('topics/<int:pk>/', views.topic_posts, name='topic_posts'),
    path('topics/<int:pk>/reply/', views.reply_topic, name='reply'),
]

JobRecruitment/urls.py
from django.contrib import admin

from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

from UserAuth import views

urlpatterns = [
    path("", include('Forum.urls')),
    # path("", views.index),
    path("admin/", admin.site.urls),
    path("auth/", include("UserAuth.urls")),
    path("info/", include("UserInfo.urls")),
    path("position/", include("PublishPosition.urls")),
    path("mdeditor/", include("mdeditor.urls")),
    path("application/", include("Application.urls")),
    path("message/", include("UserMessage.urls")),
    # path("privatemessage/", include("PrivateMessage.urls")),  # 为 PrivateMessage 设定新的路径
    path('conversation/', include('PrivateMessage.urls')),

    re_path(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
]

PublishPosition/urls.py
from django.urls import path

from PublishPosition import views

"""
should include:
/list   展示列表
view/<int: nid>/    查看编号为nid的岗位详情
publish/    发布职位
"""

app_name = "PublishPosition"
urlpatterns = [
    path("list/", views.position_list, name='publish_list'),
    path("view/<int:nid>/", views.view_position_detail, name='detail'),
    path("publish/", views.publish_position, name='publish'),
    path("modify/<int:nid>/", views.modify_position, name='modify_position'),
]

UserAuth/urls.py
from django.urls import path
from UserAuth import views


app_name = 'UserAuth'
urlpatterns = [
    path("login/", views.login, name='login'),
    path("register/", views.register, name='register'),
    path("reset/", views.reset_password, name='reset_password'),
    path("changeidentity/", views.change_identity),

    path("gencode/", views.generate_verification_code, name='gencode'),
    path("sendemail/", views.register_email, name='sendemail'),
    path("resetpasswordemail/", views.reset_password_email, name='reset_password_email'),

    path("state/", views.check_login_state),
    path("logout/", views.logout, name='logout'),

]

UserInfo/urls.py
from django.urls import path
from UserInfo import views
from UserAuth import views as auth_model

app_name = "UserInfo"
urlpatterns = [
    path("index/<int:pk>/", views.index, name='index'),
    path("resume/", views.resume, name="resume"),
    path("application/", views.apply, name='application'),
    path("myposition/", views.my_published_position, name='my_position'),
    path("info/", views.info, name='user_info'),
    path("account/", views.account, name='account'),
    path("logout/", auth_model.logout),
    path("modify/", views.modify, name='modify'),
    path("upload/", views.image_upload, name='image_upload'),
    path("resume_upload/", views.resume_upload, name="resume_upload"),
    path("resume_download/", views.resume_download),
    path('resume_remove/<int:rid>/', views.remove_resume, name="resume_remove"),
    path('show_index/', views.show_index),
    path('sendemail/', views.sendemail),
]

UserMessage/urls.py
from django.urls import path

from UserMessage import views

app_name = "UserMessage"
urlpatterns = [
    path("send/", views.send_message),
    path("list/", views.message_list, name="message_box"),
    path("view/<int:mid>/", views.view_message_detail)
]

templates/base.html
{% load static static_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Django Boards{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/js/bootstrap.bundle.min.js"></script>
    {% block stylesheet %}{% endblock %}
</head>
<body class="custom-background">

    {% block body %}
        <nav class="navbar navbar-expand-sm navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand custom-text-color" href="{% url 'Forum:home' %}">JobRecruitment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link custom-nav-link" style="margin-left: 1rem;" href="{% url 'Forum:home' %}">首页</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link custom-nav-link" style="margin-left: 1rem;" href="{% url 'PublishPosition:publish_list' %}">职位</a>
                        </li>
                    </ul>
                    <form class="d-flex" method="get" action="/position/list/">
                        <input class="form-control me-2" type="text" name="keyword" placeholder="搜索职位...">
                        <input type="hidden" name="target_place" value="0">
                        <input type="hidden" name="page" value="1">
                        <input type="hidden" name="page_size" value="10">
                        <button class="btn btn-primary custom-button" type="submit"><i class="fas fa-search"></i></button>
                    </form>
                    {% if 'UserInfo' in request.session %}
                        <div class="nav-item dropdown">
                            {% with id=request.session.UserInfo.id %}
                                <a class="nav-link dropdown-toggle" href="{% url 'UserInfo:index' id %}" id="navbardrop" data-toggle="dropdown">
                                    {% with user_id=id|stringformat:'d' %}
                                        {% with user_avatar_path="images/"|add:user_id %}
                                            {% query_image_extension user_avatar_path as user_avatar_full_path %}
                                            {% with default_avatar_path='images/default.jpeg' %}
                                                {% if user_avatar_full_path|static_file_exists %}
                                                    <img src="{% static user_avatar_full_path %}?rand=<%= Date.now() %>" alt="用户头像" class="rounded-circle" style="width:40px; height:40px;">
                                                {% else %}
                                                    <img src="{% static default_avatar_path %}" alt="默认头像" class="rounded-circle" style="width:40px; height:40px;">
                                                {% endif %}
                                            {% endwith %}
                                        {% endwith %}
                                    {% endwith %}
                                </a>
                            {% endwith %}
                            <div class="dropdown-menu">

                                <a class="dropdown-item" href="{% url 'UserInfo:resume' %}">我的简历</a>
                                <a class="dropdown-item" href="{% url 'UserInfo:application' %}">我的投递</a>
                                <a class="dropdown-item" href="{% url 'UserMessage:message_box' %}">我的收件箱</a>
                                <a class="dropdown-item" href="{% url 'UserInfo:user_info' %}">个人资料</a>
                                <a class="dropdown-item" href="{% url 'UserInfo:account' %}">账号安全</a>
                                <a class="dropdown-item" href="{% url 'UserInfo:my_position' %}">我发布的职位</a>
                                <a class="dropdown-item" href="{% url 'UserAuth:logout' %}">退出登录</a>
                            </div>
                        </div>
                        <div class="nav-item dropdown">
                            <button type="button" class="btn btn-primary custom-button dropdown-toggle" onclick="window.location.href='#'" data-toggle="dropdown">
                                发布
                            </button>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="{% url 'Forum:new_topic' %}">发动态</a>
                                <a class="dropdown-item" href="{% url 'PublishPosition:publish'%}">发职位</a>
                            </div>
                        </div>
                    {% else %}
                        <form class="form-inline ml-auto">
                            <a href="{% url 'UserAuth:login' %}" class="btn btn-outline-secondary">Log in</a>
                            <a href="{% url 'UserAuth:register' %}" class="btn btn-primary ml-2">Sign up</a>
                        </form>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="container mb-5">
            {% block content %}
            {% endblock %}
        </div>


        {% block footer %}
            <footer class="bg-dark text-muted">
                <div class="container py-4">
                    <div class="row">
                        <div class="col-md-4">
                            <h5>联系方式</h5>
                            <ul class="list-unstyled">
                                <li>电话：XXX-XXXX-XXXX</li>
                                <li>邮件：example@qq.com</li>
                                <li>地址：上海市闵行区东川路800号</li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h5>导航</h5>
                            <ul class="list-unstyled">
                                <li><a href="{% url 'Forum:home' %}" class="text-decoration-none text-secondary">首页</a></li>
                                <li><a href="#" class="text-decoration-none text-secondary">关于我们</a></li>
                                <li><a href="#" class="text-decoration-none text-secondary">服务</a></li>
                                <li><a href="#" class="text-decoration-none text-secondary">联系我们</a></li>
                            </ul>
                        </div>
                        <div class="col-md-4">
                            <h5>社交媒体</h5>
                            <ul class="list-unstyled">
                                <li><a href="https://www.facebook.com/" class="text-decoration-none text-secondary"><i class="fab fa-facebook"></i></a></li>
                                <li><a href="https://twitter.com/" class="text-decoration-none text-secondary"><i class="fab fa-twitter"></i></a></li>
                                <li><a href="https://www.instagram.com/" class="text-decoration-none text-secondary"><i class="fab fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </footer>
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
        <script>
            $(document).ready(function(){
                $(".dropdown").hover(function(){
                    var dropdownMenu = $(this).children(".dropdown-menu");
                    if(dropdownMenu.is(":visible")){
                        dropdownMenu.parent().toggleClass("open");
                    }
                });
            });

            $(document).ready(function(){
                $(document).off('click.bs.dropdown.data-api');
            });
        </script>

        {% block js %}
        {% endblock %}

    {% endblock body %}

</body>
</html>